# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.8'

services:
  customerapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: customerapi
    ports:
      - 52111:52111
    depends_on:
      - customerdb
      - redis_image
    links:
      - redis_image
  customerdb:
     image: "mcr.microsoft.com/mssql/server"
     environment:
        SA_PASSWORD: "Sqlserver@123"
        ACCEPT_EULA: "Y"
     ports:
      - 1433:1433
  redis_image:
    image: redis
    container_name: redis.cache