# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  customerapi:
    image: customerapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 52111:52111
    depends_on:
      - customerdb
  customerdb:
     image: "mcr.microsoft.com/mssql/server"
     environment:
        SA_PASSWORD: "Sqlserver@123"
        ACCEPT_EULA: "Y"
     ports:
      - 1433:1433