version: '3.3'

services:
  mccustomerapi:
    image: sudhakarsho1/customerapi:lbv1
    depends_on:
      - customerdb
      - redis_image
    links:
      - redis_image
  mcproxy:
    image: sudhakarsho1/mcproxy:lbv1
    container_name: mcproxy
    ports:
      - 52115:52115
  customerdb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Sqlserver@123"
        ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  redis_image:
    image: redis
    container_name: redis.cache
